(defparameter *nodes* '((england (tea and crumpets))
                        (france (frogs and surrender))
                        (germany (schnitzel and yelling))))
(defparameter *edges* '((england (france channel)
                                 (germany north-sea))
                        (france (germany lowlands)
                                (england channel))
                        (germany (france lowlands)
                                 (england (north-sea)))))
